.PHONY: test_triloc_1fun.out run_lost.out run_helping.out

all: 
	g++ -g -o test_triloc_1fun.out test_triloc_1fun.cpp intersection.cpp inside.cpp util.cpp -std=c++11 
	g++ -g -o run_lost.out lost_car.cpp  util.cpp tcpip.cpp -std=c++11 
	g++ -g -o run_helping.out helping_car.cpp intersection.cpp inside.cpp get_loc.cpp util.cpp tcpip.cpp -std=c++11 
	